### ISSUE TITLE
Project init

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-SDK-Android#1]

**Comment by ben181231** [comment]
- Initial structure of the project is set up. 
- An initial version `v0.0.0` is uploaded to bintray. 
- And an request to add to jCenter is sent. It is pending to be reviewed.

### Documentation

- Upload to bintray
  - Set environment variable `BINTRAY_USER` and `BINTRAY_API_KEY`
  - Run `./gradlew skygear:bintrayUpload` to bintray.

- Import to existing app
  - Include maven repo (it will not needed after jCenter includes our package)
  ```
  repositories {
    maven {
      url 'https://dl.bintray.com/skygeario/maven'
    }
  }
  ```
  - Add `compile 'io.skygear:skygear:0.0.0'` to `dependencies`
