### ISSUE TITLE
Question: CompatibleValueClasses of LambdaRequest

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/skygear-SDK-Android#105]
Currently, the CompatibleValueClasses includes Boolean, Byte, Character, Double, Float, Integer, Long, Short, String, JSONObject, and JSONArray.

However Date is not included. (Collection also...)

Since the arguments will be turn into List, then into a JSONArray. Should it accept any Class, and call the .toString() method if the class is not in CompatibleValueClasses? 

Or I should say, shall we let the parser do the parsing by its best effort, rather than limiting the Class input?

(Sorry, I don't know the implementation on server side yet)

**Comment by ben181231** [comment]
> Or I should say, shall we let the parser do the parsing by its best effort, rather than limiting the Class input?

For calling lambda functions in cloud code, I think it is caller's responsibility to serialize data into compatible values and deserialize in cloud code. Parse it by its best effort would give the uncertainty of what data format will receive to cloud code developers.

**Comment by ben181231** [comment]
By the way, for further question related to Skygear, you may try to ask on [StackOverflow](http://stackoverflow.com/questions/tagged/skygear) and tag it with `skygear`.

**Comment by chpapa** [comment]
Closing since it is question not an issue.
