### ISSUE TITLE
/device/register and /device/unregister

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/skygear-SDK-Android#107]
https://astridemo.skygeario.com/device/register
https://astridemo.skygeario.com/device/unregister

Sample app is connecting to these 2 endpoints but received 404.
Why these endpoint is being connected after login and after logout?

**Comment by ben181231** [comment]
We need to register the device for push notification purpose.

**Comment by seventhmoon** [comment]
So 404 is expected result in this sample?

**Comment by ben181231** [comment]
That should not be a 404 response. Should be 401.

**Comment by seventhmoon** [comment]
![screenshot from 2017-03-01 14-18-59](https://cloud.githubusercontent.com/assets/2444061/23448123/11e3fe22-fe8a-11e6-9c19-5c37bade0fae.png)

Arhh. Expected 401. Let me check my Interceptor again.

**Comment by seventhmoon** [comment]
`io.skygear.skygear_example E/Volley: [187] BasicNetwork.performRequest: Unexpected response code 404 for http://astridemo.skygeario.com/device/register`
`io.skygear.skygear_example W/Skygear SDK: Fail to register device token: Device not found`

I think it may be related to Emulator.

**Comment by seventhmoon** [comment]
I got 200 on my Nexus 6. So very sure that the error only occur in emulator.

**Comment by ben181231** [comment]
The [register device method](https://github.com/SkygearIO/skygear-SDK-Android/blob/1d43fad/skygear/src/main/java/io/skygear/skygear/Container.java#L288) is expected to be called in [RegistrationIntentService](https://github.com/SkygearIO/skygear-SDK-Android/blob/1d43fad/skygear/src/main/java/io/skygear/skygear/gcm/RegistrationIntentService.java#L50) which requests developers to start the service manually as [the documentation](https://docs.skygear.io/guides/push-notifications/basics/android/) states.

**Comment by seventhmoon** [comment]
So I think this is a problem on obtaining the ID in Emulator, not the SDK.
Closing this issue.
