### ISSUE TITLE
Question: Record and Reference

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/skygear-SDK-Android#108]
Is it as long as I have the id (foreign key) of the record, I could add a reference in a record using a hack like making a Map / JSON like the following?

>  {$type="ref",$id="[tablename]/[foreign key]"}

Or, If I already have the id, is it I still have to make a query first to obtain the Record Object, then make it a Reference before I do an Add Query with Reference?

**Comment by ben181231** [comment]
What you mentioned is the internal representation for a record reference in Skygear.

It is suggested to create a reference from a Skygear record as [the documentation](https://docs.skygear.io/guides/cloud-db/data-types/android/) mentioned, although it is valid to create a reference from record type and record id as [the test case](https://github.com/SkygearIO/skygear-SDK-Android/blob/2c51605/skygear/src/androidTest/java/io/skygear/skygear/ReferenceUnitTest.java#L14) does.

**Comment by ben181231** [comment]
By the way, for further question related to Skygear, you may try to ask on [StackOverflow](http://stackoverflow.com/questions/tagged/skygear) and tag it with `skygear`.
