### ISSUE TITLE
Broken Link in README.md

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/skygear-SDK-Android#110]
The link (https://docs.skygear.io/android/build/skygear-example-latest.apk) to the Sample APK is broken.

**Comment by ben181231** [comment]
Oh... That is accidentally deleted. Will be uploaded it back.

**Comment by chpapa** [comment]
@ben181231 seems the file have not been uploaded back? Have the Skygear DOC IAM change in README.md been deployed to production?

**Comment by ben181231** [comment]
> @ben181231 seems the file have not been uploaded back?

Should be uploaded. Let me verify it.

> Have the Skygear DOC IAM change in README.md been deployed to production?

Yes. It is applied.

**Comment by ben181231** [comment]
@chpapa

> > @ben181231 seems the file have not been uploaded back?
>
> Should be uploaded. Let me verify it.

Uploaded.
