### ISSUE TITLE
Discover user by email/username API

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-SDK-Android#119]
This issue is for tracking of discover user by email/username API in Android SDK.

In JS / iOS SDK, there are discover users related functions. Please find the related API doc:

http://cocoadocs.org/docsets/SKYKit/0.22.1/Classes/SKYUserDiscoverPredicate.html
https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/container.js~Container.html#instance-method-discoverUserByEmails

It seems Android SDK is missing similar API.

If we confirm there are no such API, we should implement it in Android as it is essential for many use cases (for example, for a chat app to implement a "Find friends by email" interface)

**Comment by rickmak** [comment]
I can confirm you there is no implementation on `userDiscover` at Android. It currently only have `user:query` which is intended for admin use.

**Comment by chpapa** [comment]
@rickmak Thanks. I will leave this issue here for implementation of userDiscover.

**Comment by chpapa** [comment]
Closing this issue as we will start to redesign user discoverability and profile.
