### ISSUE TITLE
Support HashTable / HashMap as arguments for callLambdaFunction

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-SDK-Android#120]
In Android SDK, there is a function:
`callLambdaFunction(java.lang.String name, java.lang.Object[] args, LambdaResponseHandler handler)`

As mentioned at SkygearIO/guides#48, Javascript support both array and hashtable for positional / named arguments of Lambda function.

So for consistency, Android should have something like:
`callLambdaFunction(java.lang.String name, java.util.Map<String, Object> args, LambdaResponseHandler handler)`

**Comment by seventhmoon** [comment]
Why `HashTable`, not `Map`?

**Comment by chpapa** [comment]
> Why Hashtable, not Map?

Good point, changed the original description.
