### ISSUE TITLE
Update SDK API Grouping

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/skygear-SDK-Android#133]
https://github.com/SkygearIO/features/pull/71

- [ ] Update Container api with the following grouping
- [ ] Update Test
- [ ] Update Example

Grouping:
```
Container:

  state:
    url
    apiKey
    timeoutOptions
    auth(AuthContainer)
    relation(RelationContainer)
    db(DatabaseContainer)
    pubsub(PubsubContainer)
    push(PushContainer)
    chat(ChatContainer)
    analytics(AnalyticsContainer)

  api:
    config
    configApiKey
    lambda
    sendRequestObject
    makeRequest


AuthContainer:

  state:
    accessToken
    user(User)

  api:
    signupWithUsername
    signupWithEmail
    signupWithUsernameAndProfile
    signupWithEmailAndProfile
    signupAnonymously
    loginWithUsername
    loginWithEmail
    loginWithProvider
    logout
    changePassword
    forgotPassword
    // following api would be affected by https://github.com/SkygearIO/features/pull/68
    saveUser
    whoami
    getUsersByEmail
    getUsersByUsername
    discoverUserByEmails
    discoverUserByUsernames


RelationContainer:

  api:
    queryFriend
    queryFollower
    queryFollowing
    addRelation
    removeRelation


DatabaseContainer:

  state:
    public(PublicDatabase)
    private(PrivateDatabase)
    cacheResponse(Boolean)

  api:
    makeUploadAssetRequest


PublicDatabase:

  state:
    cacheStore

  api:
    setAdminRole
    setDefaultRole
    getDefaultACL
    setDefaultACL
    setRecordCreateAccess
    setRecordDefaultAccess
    getRecordByID
    save
    query
    del
    clearCache
    fetchSubscriptionWithID
    saveSubscription
    deleteSubscriptionWithID


PrivateDatabase:

  state:
    cacheStore

  api:
    getRecordByID
    save
    query
    del
    clearCache
    fetchSubscriptionWithID
    saveSubscription
    deleteSubscriptionWithID


PubsubContainer:

  state:
    channel
    internalChannel
    autoPubsub(Boolean)

  api:
    on
    off

PushContainer:

  state:
    deviceToken
    deviceID

  api:
    registerDevice
    unregisterDevice
    sendPushNotification

ChatContainer:


AnalyticsContainer:

```

Example:
```
// Call API
import android.content.Context;
import io.skygear.skygear.Container;
import io.skygear.skygear.Record;

Container container = Container.defaultContainer(Context.getApplicationContext());
container.auth().loginWithEmail("email@example.com", "secret");
container.auth().forgotPassword("email@example.com");
container.pubsub().subscribe("channel", new Pubsub.Handler());

Record sampleItem = new Record('SampleItem');
container.db().public().save(sampleItem, null);
```
```
// Retrieve contexts
import android.content.Context;
import io.skygear.skygear.Container;

Container container = Container.defaultContainer(Context.getApplicationContext());
String apiKey = container.apiKey();
String currentAccessToken = container.auth().currentAccessToken();
Map publicDBCache = container.db().public().cache();
```

**Comment by seventhmoon** [comment]
I am thinking should the call looks a like the pattern `Glide` and `Picasso` are using.
e.g. 
```
GlideApp
    .with(myFragment)
    .load(url)
    .centerCrop()
    .placeholder(R.drawable.loading_spinner)
    .into(myImageView);
```

So,  
`container.auth().loginWithEmail("email@example.com", "secret");`
could be 
`SkygearAuth.with(container).loginWithEmail("email@example.com", "secret");`
which is more human readable.

**Comment by Steven-Chan** [comment]
I think `SkygearAuth.with(container)` might be more match the java/android convention, but `container.auth()` is not that bad actually while it matches the pattern with other skygear sdk.

@rickmak @cheungpat have any comment?

**Comment by seventhmoon** [comment]
A method usually refer to an action related to the method name.
However, container.auth() is not doing an action of "Auth" ...
which may be confusing...

**Comment by Steven-Chan** [comment]
Indeed, `container.auth()` might look a bit confusing for it is not doing any action. What about `container.getAuth()` or even `container.auth`.

One of the original purpose of api grouping is to make various api more discoverable. Everything are built under the `container` object, then api can be found with IDE auto-complete with ease. I think this behaviour better be remained.

If using `SkygearAuth`, then user would first need to know `Skygear` as a class prefix first.

Another reason is that currently all classes do not have `Skygear` prefix, so it would be inconsistent, or a big change to the SDK.

**Comment by seventhmoon** [comment]
But actually, `SkygearAuth.with(container)` is more similar to current Skygear-chat.
```
mSkygear = Container.defaultContainer(this);
mChatContainer = ChatContainer.getInstance(mSkygear);
```

So, is it going to **group** or **modularize**?

**Comment by Steven-Chan** [comment]
Actually we have gone through the discussion between `skygearAuth vs skygear.auth` in https://github.com/SkygearIO/features/issues/70 and we have chosen `skygear.auth`.

We have had further discussion on considering the `SkygearAuth.with(container)` pattern, and we still think `skygear.auth` is a better choice for our purpose of the issue. The main reason is that it is better for developer to discover api of different features, on both IDE and generated doc.
