### ISSUE TITLE
AuthContainer.resetPassword is not passing Date argument correctly

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/skygear-SDK-Android#213]
In `AuthContainer.resetPassword`, it directly passes a `Date` object to `callLambdaFunction`. However, `callLambdaFunction` does not accept `Date` as argument type.

Exception stack trace:
```
java.security.InvalidParameterException: Argument at index 2 is incompatible
                                                       at io.skygear.skygear.q.<init>(LambdaRequest.java:64)
                                                       at io.skygear.skygear.m.a(Container.java:210)
                                                       at io.skygear.skygear.h.a(AuthContainer.java:374)
```

**Comment by carmenlau** [comment]
@howawong Warm reminder, please also test the other platforms SDK, thanks!!

**Comment by howawong** [comment]
@carmenlau  checked.  The [plugin](https://github.com/SkygearIO/forgot_password/blob/a193a564ca66122dcd74c20b21809c281972f79f/forgot_password/handlers/util/user.py#L99) should only accept integer timestamp 

But Android SDK sends `Date` while iOS SDK sends `NSDate`, only JS API reference states the field is a timestamp.

**Comment by carmenlau** [comment]
Opened issue in iOS https://github.com/SkygearIO/skygear-SDK-iOS/issues/183

**Comment by carmenlau** [comment]
Please update error message of example:
https://github.com/SkygearIO/skygear-SDK-Android/pull/215#discussion_r173712857
