### ISSUE TITLE
Bug on SkyGear Chat demo : Application restarts Upon cancellation of Activation Mode

### ISSUE THREAD

**Issue by gutzygwin** [SkygearIO/skygear-SDK-Android#223]
#### Expected behavior
Skygear is an open source andriod application which is used for conversing with other users online. Skygear provides the basic ammenities or less of a social application. This feature in consideration in this contribution is the working function of the application to run and carry out activities  properly. 

#### Actual behavior
The activities carried out on the app's interface are cleared and refreshed upon cancellation of airplane mode. This fault here most times causes the application to hang or crash. As to test-run the application, i performed some actions like creating some conversations so the application interface wont be empty, then i activated and de-activate airplane mode and application hanged. 

#### How to reproduce
* Download Skygear from Google Playstore. 
* Log in on the application and Sign up if you haven't joined. 
* (make sure to leave some work on the display on application) this is to make the bug show true effecct. 
* activate the airplane mode and de-activate it. 
* Application refreshes and hangs. 

--------------------------------------------------------

* Version of the add application: 1.2
* Last updated: February 14, 2018

-------------------------------------------------------

* Browser: Google Playstore / Skygear 
* Operating system: Android 7.0

#### Recording Of The Bug

https://youtu.be/Dif6puW1x3U
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-skygear-chat-demo-application-restarts-upon-cancellation-of-activation-mode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by chpapa** [comment]
@carmenlau  looks like it should be easily verifiable, if it is true can you move the issue to Android chat demo and have a higher priority to fix it?

**Comment by carmenlau** [comment]
OK, let me check:)

**Comment by carmenlau** [comment]
@gutzygwin Thanks for your report. We checked your bug reports, we can reproduce #224 #225 #226. It is because your username has a tailing space. The crash is not expected and we created issue in https://github.com/SkygearIO/chat-SDK-Android/issues/185 to follow up and fix.

For this issue #223, we cannot reproduce. We tried turning on and off airplane mode, and also using proxy to simulate poor network. Please let me know if you have more information that can help us to debug.

Thanks again!!
