### ISSUE TITLE
Bug on SkyGear Chat demo : Application crashes when trying to send images from gallery

### ISSUE THREAD

**Issue by gutzygwin** [SkygearIO/skygear-SDK-Android#224]
#### Expected behavior
On thy skygear chat demo which is an open source application for creating conversations, etc, it is expected to complete certain functions like uploading an image on the application with the aid of the **select images from gallery** option provided on the **+** icon just at the buttom left corner of the conversation/chat.

#### Actual behavior
Upon click on the **+** icon and then clicking on **select image from gallery** , then selecting a random image from the gallery to upload, the application crashes. 

#### How to reproduce
* Download Skygear chat demo from Google Playstore.
* Sign up on the application. 
* log in with details.
* create a conversation with one or two or more persons. 
* Enter the conversation and click on the **+** button at the buttom left corner of the screen. 
* click on **select image from gallery.**
* choose a random image to upload.
* application crashes. 

--------------------------------------------------------

* Version of the application: version 1.2
* last updated : feb 14, 2018.

--------------------------------------------------------

* Browser: Google Playstore / Skygear 
* Operating system: Andriod 7.0

#### Recording Of The Bug

https://youtu.be/suJBf41FUMo
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-skygear-chat-demo-application-crashes-when-trying-to-send-images-from-gallery">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by carmenlau** [comment]
Follow up here: https://github.com/SkygearIO/chat-SDK-Android/issues/185
