### ISSUE TITLE
Bug on SkyGear Chat demo : Application crashes when trying to record/upload a voice note in conversations

### ISSUE THREAD

**Issue by gutzygwin** [SkygearIO/skygear-SDK-Android#225]
#### Expected behavior
Skygear chat demo is an open source andriod application which provides user with the avenue for conversing with other users online. The function of this particular app in consideration is the **recording/uploading voice note** function. As expected by the application, the voice note feature of the application is to carry out certain functions as recording voice notes by user and uploading them. 

#### Actual behavior
Upon recording voice notes using the voice note recorder function when in a conversation on the application, the application crashes.

#### How to reproduce
* Download the skygear chat demo application on Google playstore. 
* log into the application if you are already a user, if you aren't, you can sign up first. 
* start a conversation by adding two or three people on thr conversation. 
* enter the conversation By clicking on enter. 
* record and upload a voice note by holding on to the voice note recorder button. 
* release the button after recording.
* application crashes. 

--------------------------------------------------------

* version of the application: version 1.2
* last updated: February 14, 2018.

--------------------------------------------------------

* Browser: Google playstore / skygear chat demo
* Operating system: Andriod 7.0 . Infinix Note 4.

#### Recording Of The Bug

https://youtu.be/eMihe-g7tTE
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-skygear-chat-demo-application-crashes-when-trying-to-record-upload-a-voice-note-in-conversations">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by carmenlau** [comment]
Follow up here: https://github.com/SkygearIO/chat-SDK-Android/issues/185
