### ISSUE TITLE
Bug on Skygear Chat Demo: Application Crashes when attempting to send a message in conversations

### ISSUE THREAD

**Issue by gutzygwin** [SkygearIO/skygear-SDK-Android#226]
#### Expected behavior
The Open source application, skygear chat demo is a wonderful social-media application that encourages the use of conversations which do appear in form of a chat room. The recent version on the Application has been faulty **(concurring)** and this expected feauture in consideration here is the **send message** function which required to send a message being typed to the conversation. 

#### Actual behavior
I notice that after typing out the message on conversation and upon clicking the **send** button, the application crashes. 

#### How to reproduce
* Download Skygear Chat demo Application from Google playstore. 
* sign up in the application. 
* log into the application. 
* create conversation with a group of people and enter into conversation. 
* type out a message on the conversation and click send. 
* application crashes. 

--------------------------------------------------------
* version of the application: **v 1.2**
* last updated: **Feb 14, 2018**

--------------------------------------------------------

* Browser: Google playstore / skygear
* Operating system: Android 7.0

#### Recording Of The Bug

https://youtu.be/MS9hGQ7oaYM
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-skygear-chat-demo-application-crashes-when-attempting-to-send-a-message-in-conversations">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by carmenlau** [comment]
Follow up here: https://github.com/SkygearIO/chat-SDK-Android/issues/185
