### ISSUE TITLE
RecordSerializer fails on empty array

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-Android#23]
The RecordSerializer failed to parse an empty json array. e.g. for a json response {"participant_ids":[]} the SDK will throw InvalidParameterException at io.skygear.skygear.Record@set(String, Object), when it parse the "[]",

But it parse okay on non empty array.

**Comment by ben181231** [comment]
Just verified. Currently `RecordSerializer` will fail to deserialize `JSONArray` fields and `JSONObject` fields.

**Comment by rickmak** [comment]
Fixed at f3c3291
