### ISSUE TITLE
Failed to re-construct a Record from json string produced by SDK

### ISSUE THREAD

**Issue by cpryanpang** [SkygearIO/skygear-SDK-Android#45]
After we serialize a `Record` into a `JSONObject` (and/or further encode it as a json-string), it is unable to re-construct the same `Record`.

- Skygear Android SDK: 0.16.0

## Steps to reproduce:
Followed is just sample code to illustrate the issue; not a usual practice in reality.
```
	Record source = new Record("user"); // simply create a record of any record type
	JSONObject jsonObject = source.toJson();

	try {
		Record destination = Record.fromJson(jsonObject);
	} catch (JSONException e) {
		Log.e(LOG_TAG, e.getMessage(), e);
	}
```

Above code yields below error:
```
 org.json.JSONException: No value for _created_at
     at org.json.JSONObject.get(JSONObject.java:354)
     at org.json.JSONObject.getString(JSONObject.java:514)
     at io.skygear.skygear.RecordSerializer.deserialize(RecordSerializer.java:148)
     at io.skygear.skygear.Record.fromJson(Record.java:404)
     ....
```

Guess that `RecordSerializer#serialize` didn't serialize `_created_at`, `_updated_at`, `_created_by`, `_updated_by`, `_ownerID`, etc....
But `RecordSerializer#deserialize` will (try to) deserialize these fields, resulting `org.json.JSONException: No value for _created_at`

## Real use case
Sometime we need to pass `Record` via `Intent`, between `Activity`s / `Fragment`s:
```
	Record source = new Record("user");
	String jsonString = source.toJson().toString();
	
	Bundle bundle = new Bundle();
	bundle.putString("jsonString", jsonString);
	
	Intent intent = new Intent(getContext(), NextActivity.class);
	startActivity(intent);
```

Then in `NextActivity#onCreate`, we extract the string and re-construct the `Record`:
```
	try {
		Record destination = Record.fromJson(new JSONObject(getIntent().getStringExtra("jsonString")));
	} catch (JSONException e) {
		Log.e(LOG_TAG, e.getMessage(), e);
	}
```
The same error would occur.

**Comment by ben181231** [comment]
Fix on Commit df3b022

**Comment by cpryanpang** [comment]
The commit only enhanced the deserialization process by preventing parsing-exception on missing fields.

Yet it is also meaningful to serialize those meta fields into JSONObject, isn't it? Otherwise it is still unable to replicate / persist the same `Record` over different Android components. Is it practical to modify `RecordSerializer#serialize` too?

**Comment by ben181231** [comment]
Added the meta fields on Commit 51054bd
