### ISSUE TITLE
VolleyPlus or Volley?

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/skygear-SDK-Android#99]
Shall this library use volley (compile 'com.android.volley:volley:1.0.0') or volleyplus (compile 'dev.dworks.libs:volleyplus:0.1.4')?

It is been a long time since volleyplus last updated.

Understand that volleyplus is based on volley, but seems some of the API signature are different. (using old version of Volley?)

Is it better to use Volley, and add the implementation of JsonRequest, MultipartRequest back?

**Comment by ben181231** [comment]
I think it is okay to change back to `volley` and add the implementation of `MultipartRequest`.
Would you like send us a PR about that? 😅 

Actually the SDK was using `volley` before the Commit d770ec8. The `MultipartRequest` would be the main reason we change to use `volleyPlus`.

**Comment by seventhmoon** [comment]
I made similar item like GsonRequest before.

So my approach will be making a Volley Expansion Pack containing all these self make request handler while using official Volley as underlying.

**Comment by seventhmoon** [comment]
https://github.com/seventhmoon/VolleyEx
works with skygear_sample
let me tidy up first

**Comment by ben181231** [comment]
👍

**Comment by seventhmoon** [comment]
I think it is more than a wish.
My upper layer implementation also use Volley.  
But I cannot have both Volley and VolleyPlus at the same time (same package and class name)
VolleyPlus a mod of Volley package.
It will be good if VolleyPlus could fix this problem. (but no recent update already)
And it is not good to ask all developer using Volley at the same time to switch to VolleyPlus.

**Comment by chpapa** [comment]
@seventhmoon solid point. Let me add it to our Product Meeting... meanwhile see if anyone would have time to fix the Pull Request #100
